/*
 * EasyPeasy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AnimalHead : IEquatable<AnimalHead>
    {
        /// <summary>
        /// Gets or Sets Hairs
        /// </summary>
        [DataMember(Name="hairs", EmitDefaultValue=true)]
        public Object Hairs { get; set; }


        /// <summary>
        /// Gets or Sets Tongue
        /// </summary>
        
        public enum TongueEnum
        {
            
            /// <summary>
            /// Enum LongEnum for long
            /// </summary>
            
            LongEnum = long,
            
            /// <summary>
            /// Enum ShortEnum for short
            /// </summary>
            
            ShortEnum = short
        }

        /// <summary>
        /// Gets or Sets Tongue
        /// </summary>
        [DataMember(Name="tongue", EmitDefaultValue=true)]
        public TongueEnum? Tongue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AnimalHead {\n");
            sb.Append("  Hairs: ").Append(Hairs).Append("\n");
            sb.Append("  Tongue: ").Append(Tongue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AnimalHead)obj);
        }

        /// <summary>
        /// Returns true if AnimalHead instances are equal
        /// </summary>
        /// <param name="other">Instance of AnimalHead to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnimalHead other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Hairs == other.Hairs ||
                    Hairs != null &&
                    Hairs.Equals(other.Hairs)
                ) && 
                (
                    Tongue == other.Tongue ||
                    
                    Tongue.Equals(other.Tongue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Hairs != null)
                    hashCode = hashCode * 59 + Hairs.GetHashCode();
                    
                    hashCode = hashCode * 59 + Tongue.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AnimalHead left, AnimalHead right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AnimalHead left, AnimalHead right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
